apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rent-right-searcher
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rent-right-searcher
            image: gcr.io/rent-right-dev/rent-right-searcher:latest
            imagePullPolicy: Always
            volumeMounts:
            - name: credentials-volume
              mountPath: /opt/rent-right-searcher/creds
          volumes:
          - name: config-volume
            configMap:
              name: searcher-config
          - name: credentials-volume
            secret:
              secretName: searcher-secret
          restartPolicy: Never