apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: rent-right-searcher
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rent-right-searcher
            image: gcr.io/rent-right-dev/rent-right-searcher:latest
            imagePullPolicy: Always
            volumeMounts:
            - name: credentials-volume
              mountPath: /opt/rent-right-searcher/creds
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/opt/rent-right-searcher/creds/rent-right-dev.json"
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: base-url-secret
                  key: BASE_URL
            - name: PROXY
              valueFrom:
                secretKeyRef:
                  name: proxy-secret
                  key: PROXY
          volumes:
          - name: credentials-volume
            secret:
              secretName: credentials-secret
          restartPolicy: Never
      activeDeadlineSeconds: 600
